# Reference: https://github.com/Golf-Drill-Challenge-App/Golf-App/blob/layout/.github/workflows/main.yml

name: Prettier Code Check

on: [pull_request]

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Use whatever node version your project requires
      - name: Install Prettier
        run: npm add prettier --dev
      - name: Check code formatting
        run: npm run pretty:check